import type { AgentDashboardData } from '@/lib/types';

// This data is used as a fallback when live data cannot be fetched from Firestore.
export const mockAgentDashboardData: AgentDashboardData = {
    userId: 'agent-1',
    leadIndicatorGrade: 'A',
    leadIndicatorPerformance: 99,
    isLeadIndicatorGracePeriod: false,
    incomeGrade: 'A',
    incomePerformance: 99,
    isIncomeGracePeriod: false,
    expectedYTDIncomeGoal: 30000,
    ytdTotalPotential: 39000,
    pipelineAdjustedIncome: { grade: 'A', performance: 110 },
    kpis: {
        calls: { actual: 1250, target: 1500, performance: 83, grade: 'C' },
        engagements: { actual: 420, target: 500, performance: 84, grade: 'C' },
        appointmentsSet: { actual: 50, target: 55, performance: 91, grade: 'B' },
        appointmentsHeld: { actual: 45, target: 50, performance: 90, grade: 'B' },
        contractsWritten: { actual: 15, target: 12, performance: 125, grade: 'A' },
        closings: { actual: 9, target: 8, performance: 113, grade: 'A' },
    },
    netEarned: 27000,
    netPending: 12000,
    monthlyIncome: [
        { month: 'Jan', closed: 3000, pending: 1000, goal: 2500 },
        { month: 'Feb', closed: 3500, pending: 500, goal: 2500 },
        { month: 'Mar', closed: 2500, pending: 2000, goal: 2500 },
        { month: 'Apr', closed: 4000, pending: 0, goal: 2500 },
        { month: 'May', closed: 2000, pending: 3000, goal: 2500 },
        { month: 'Jun', closed: 5000, pending: 1500, goal: 2500 },
        { month: 'Jul', closed: 0, pending: 2000, goal: 2500 },
        { month: 'Aug', closed: 0, pending: 1000, goal: 2500 },
        { month: 'Sep', closed: 0, pending: 0, goal: 2500 },
        { month: 'Oct', closed: 0, pending: 0, goal: 2500 },
        { month: 'Nov', closed: 0, pending: 0, goal: 2500 },
        { month: 'Dec', closed: 0, pending: 0, goal: 2500 },
    ],
    totalClosedIncomeForYear: 27000,
    totalPendingIncomeForYear: 12000,
    totalIncomeWithPipelineForYear: 39000,
    forecast: { projectedClosings: 11, paceBasedNetIncome: 33000 },
    conversions: {
        callToEngagement: { actual: 0.336, plan: 0.25 },
        engagementToAppointmentSet: { actual: 0.119, plan: 0.1 },
        appointmentSetToHeld: { actual: 0.9, plan: 0.9 },
        appointmentHeldToContract: { actual: 0.333, plan: 0.2 },
        contractToClosing: { actual: 0.6, plan: 0.8 },
    },
    stats: {
        ytdVolume: 2700000,
        avgSalesPrice: 300000,
        buyerClosings: 6,
        sellerClosings: 3,
        renterClosings: 0,
        avgCommission: 3000,
        engagementValue: 64.28,
    },
};
