import 'server-only';
import { adminAuth, adminDb } from '@/lib/firebase/admin';
import { isStaff } from '@/lib/auth/staffAccess';

export const SMART_FORMS_URL = 'https://smartforms-kxlzueqw.manus.space';
export const SMART_FORMS_SUBCOLLECTION = 'smartForms';
export function getBearer(req: Request) { const header = req.headers.get('authorization') || ''; return header.startsWith('Bearer ') ? header.slice(7).trim() : null; }
export async function smartFormsCaller(req: Request) { const token = getBearer(req); if (!token) throw new Error('Sign in is required.'); const decoded = await adminAuth.verifyIdToken(token); return { uid: decoded.uid, name: decoded.name || decoded.email || 'User', isStaff: await isStaff(decoded.uid) }; }
async function agentIdsFor(uid: string) { const ids = new Set<string>([uid]); const byId = await adminDb.collection('agentProfiles').doc(uid).get().catch(() => null); if (byId?.exists) { const data = byId.data() || {}; ids.add(byId.id); if (data.agentId) ids.add(String(data.agentId)); if (data.firebaseUid) ids.add(String(data.firebaseUid)); } const byFirebase = await adminDb.collection('agentProfiles').where('firebaseUid', '==', uid).limit(1).get().catch(() => null); if (byFirebase && !byFirebase.empty) { const data = byFirebase.docs[0].data() || {}; ids.add(byFirebase.docs[0].id); if (data.agentId) ids.add(String(data.agentId)); if (data.firebaseUid) ids.add(String(data.firebaseUid)); } return ids; }
export async function getAuthorizedTransaction(req: Request, txId: string) { const user = await smartFormsCaller(req); const snapshot = await adminDb.collection('transactions').doc(txId).get(); if (!snapshot.exists) throw new Error('Transaction not found.'); const transaction = snapshot.data() || {}; if (user.isStaff) return { user, transaction, ref: snapshot.ref }; const ids = await agentIdsFor(user.uid); const match = [transaction.agentId, transaction.coAgent1Id, transaction.coAgent2Id, transaction.coAgent3Id, transaction.coAgent?.agentId, transaction.coAgentId].filter(Boolean).map(String).some((id) => ids.has(id)); if (!match) throw new Error('You do not have access to this transaction.'); return { user, transaction, ref: snapshot.ref }; }
export function serialize(value: any): any { if (!value) return value ?? null; if (typeof value.toDate === 'function') return value.toDate().toISOString(); if (Array.isArray(value)) return value.map(serialize); if (typeof value === 'object') return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, serialize(item)])); return value; }
