import 'server-only';
import { adminAuth, adminDb } from '@/lib/firebase/admin';
import { isStaff } from '@/lib/auth/staffAccess';

export const SMART_PROPERTY_URL = 'https://smartflip-rxtcvbcs.manus.space';
export const SMART_PROPERTY_SUBCOLLECTION = 'investmentScenarios';
export function authorization(req: Request) { const header = req.headers.get('authorization') || ''; return header.startsWith('Bearer ') ? header.slice(7).trim() : null; }
export async function propertyCaller(req: Request) { const token = authorization(req); if (!token) throw new Error('Sign in is required.'); const decoded = await adminAuth.verifyIdToken(token); return { uid: decoded.uid, name: decoded.name || decoded.email || 'User', isStaff: await isStaff(decoded.uid) }; }
async function identities(uid: string) { const ids = new Set<string>([uid]); const direct = await adminDb.collection('agentProfiles').doc(uid).get().catch(() => null); if (direct?.exists) { const data = direct.data() || {}; ids.add(direct.id); if (data.agentId) ids.add(String(data.agentId)); if (data.firebaseUid) ids.add(String(data.firebaseUid)); } const canonical = await adminDb.collection('agentProfiles').where('firebaseUid', '==', uid).limit(1).get().catch(() => null); if (canonical && !canonical.empty) { const data = canonical.docs[0].data() || {}; ids.add(canonical.docs[0].id); if (data.agentId) ids.add(String(data.agentId)); if (data.firebaseUid) ids.add(String(data.firebaseUid)); } return ids; }
export async function getPropertyTransaction(req: Request, txId: string) { const user = await propertyCaller(req); const snapshot = await adminDb.collection('transactions').doc(txId).get(); if (!snapshot.exists) throw new Error('Transaction not found.'); const transaction = snapshot.data() || {}; if (user.isStaff) return { user, transaction, ref: snapshot.ref }; const own = await identities(user.uid); const permitted = [transaction.agentId, transaction.coAgent1Id, transaction.coAgent2Id, transaction.coAgent3Id, transaction.coAgent?.agentId, transaction.coAgentId].filter(Boolean).map(String).some((value) => own.has(value)); if (!permitted) throw new Error('You do not have access to this transaction.'); return { user, transaction, ref: snapshot.ref }; }
export function investmentContext(transaction: Record<string, any>, txId: string) { return { transactionId: txId, property: String(transaction.address || ''), purchasePrice: transaction.salePrice ?? transaction.purchasePrice ?? transaction.commercialSalePrice ?? null, rent: transaction.monthlyRent ?? transaction.commercialLeaseMonthly ?? transaction.estimatedRent ?? null, taxes: transaction.propertyTaxes ?? transaction.annualPropertyTaxes ?? null, insurance: transaction.insurance ?? transaction.annualInsurance ?? null, hoa: transaction.hoaFee ?? transaction.monthlyHoa ?? null, propertyType: String(transaction.propertyType || transaction.transactionType || ''), clientName: String(transaction.clientName || ''), agentId: String(transaction.agentId || '') }; }
export function serializeProperty(value: any): any { if (!value) return value ?? null; if (typeof value.toDate === 'function') return value.toDate().toISOString(); if (Array.isArray(value)) return value.map(serializeProperty); if (typeof value === 'object') return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, serializeProperty(item)])); return value; }
