import 'server-only';
import { adminAuth, adminDb } from '@/lib/firebase/admin';
import { isAdminLike } from '@/lib/auth/staffAccess';
import { sendNotification } from '@/lib/notifications/sendNotification';

export const HUB_POSTS = 'hubPosts';
export const HUB_VIEWS = 'hubPostViews';
export const HUB_RSVPS = 'hubEventRsvps';
export type HubCategory = 'announcement' | 'company_update' | 'event' | 'training' | 'webinar' | 'meeting' | 'agent_development' | 'reminder' | 'resource' | 'link' | 'document' | 'video';
export type HubStatus = 'draft' | 'scheduled' | 'published' | 'unpublished' | 'archived';
export type HubAudience = { everyone?: boolean; roles?: string[]; officeIds?: string[]; teamIds?: string[]; userIds?: string[]; groupIds?: string[] };
export function bearer(req: Request) { const value = req.headers.get('authorization') || ''; return value.startsWith('Bearer ') ? value.slice(7).trim() : null; }
export async function hubCaller(req: Request) { const token = bearer(req); if (!token) throw new Error('Unauthorized'); const decoded = await adminAuth.verifyIdToken(token); return { uid: decoded.uid, name: decoded.name || decoded.email || 'User', email: decoded.email || '', isAdmin: await isAdminLike(decoded.uid) }; }
export function timestamp(value: any) { return value?.toDate?.().toISOString?.() || value || null; }
export function publicHubPost(id: string, data: Record<string, any>) { return { id, title: data.title || '', body: data.body || '', category: data.category || 'announcement', status: data.status || 'draft', featured: Boolean(data.featured), pinned: Boolean(data.pinned), audience: data.audience || { everyone: true }, resources: Array.isArray(data.resources) ? data.resources : [], event: data.event || null, publishedAt: timestamp(data.publishedAt), scheduledFor: timestamp(data.scheduledFor), createdAt: timestamp(data.createdAt), updatedAt: timestamp(data.updatedAt), createdByName: data.createdByName || null, requiresAcknowledgment: Boolean(data.requiresAcknowledgment) }; }
export function audienceFromBody(value: any): HubAudience { const source = value && typeof value === 'object' ? value : {}; const stringArray = (item: any) => Array.isArray(item) ? [...new Set(item.filter((v) => typeof v === 'string' && v.trim()).map((v) => v.trim().slice(0, 100)))] : []; return { everyone: Boolean(source.everyone), roles: stringArray(source.roles), officeIds: stringArray(source.officeIds), teamIds: stringArray(source.teamIds), userIds: stringArray(source.userIds), groupIds: stringArray(source.groupIds) }; }
export async function resolveAudience(audience: HubAudience) { const users = await adminDb.collection('users').limit(2000).get(); const profiles = await adminDb.collection('agentProfiles').limit(2000).get(); const profilesByUid = new Map(profiles.docs.map((doc) => [String(doc.data().firebaseUid || doc.id), { id: doc.id, ...doc.data() }])); const filters = [audience.roles?.length, audience.officeIds?.length, audience.teamIds?.length, audience.userIds?.length, audience.groupIds?.length].some(Boolean); return users.docs.filter((doc) => { const uid = doc.id; const user = doc.data() as Record<string, any>; const profile = (profilesByUid.get(uid) || {}) as Record<string, any>; if (audience.everyone && !filters) return true; const roles = [String(user.role || ''), String(profile.role || ''), String(user.staffRole || '')]; const offices = [String(profile.officeId || profile.office || user.officeId || user.office || '')]; const teams = [String(profile.primaryTeamId || profile.teamId || user.teamId || '')]; const groups = [...(Array.isArray(profile.hubGroupIds) ? profile.hubGroupIds : []), ...(Array.isArray(user.hubGroupIds) ? user.hubGroupIds : [])].map(String); return Boolean(audience.everyone || audience.userIds?.includes(uid) || audience.roles?.some((value) => roles.includes(value)) || audience.officeIds?.some((value) => offices.includes(value)) || audience.teamIds?.some((value) => teams.includes(value)) || audience.groupIds?.some((value) => groups.includes(value))); }).map((doc) => doc.id); }
export async function visibleTo(userUid: string, data: Record<string, any>) { return (await resolveAudience(audienceFromBody(data.audience))).includes(userUid); }
export async function notifyHubPost(postId: string, post: Record<string, any>) { const recipients = await resolveAudience(audienceFromBody(post.audience)); const delivery = post.deliveryChannels || { inApp: true, email: false, sms: false }; await Promise.all(recipients.map(async (recipientUid) => { await adminDb.collection('hubPostDeliveries').doc(`${postId}_${recipientUid}`).set({ postId, recipientUid, status: 'notification_requested', channels: delivery, createdAt: new Date(), updatedAt: new Date() }, { merge: true }); })); await sendNotification(adminDb, { type: 'hub_post_published', recipientUids: recipients, title: post.title, body: String(post.body || '').slice(0, 240), url: `/dashboard/hub?post=${postId}`, data: { hubPostId: postId }, channels: { in_app: delivery.inApp ? undefined : false, email: delivery.email ? undefined : false, sms: delivery.sms ? undefined : false, push: false } }); return recipients.length; }
