import 'server-only';
import { addMonths, differenceInDays, endOfYear, startOfYear } from 'date-fns';
import { resolveGCI } from '@/lib/commissions';
import type { AnniversaryYearProgress, QualificationProgress } from '@/lib/types/incentives';
import type { RecruitingIncentiveConfig } from '@/lib/types/recruitingConfig';

export function recruitingDate(raw: any): Date | null { if (!raw) return null; if (typeof raw.toDate === 'function') return raw.toDate(); if (typeof raw === 'string' || raw instanceof Date) { const parsed = new Date(raw); return Number.isNaN(parsed.getTime()) ? null : parsed; } return null; }
export function transactionGci(transaction: Record<string, any>): number { const snapshot = Number(transaction.splitSnapshot?.grossCommission); if (Number.isFinite(snapshot) && snapshot > 0) return snapshot; return resolveGCI({ commissionBasePrice: transaction.commissionBasePrice, salePrice: transaction.salePrice, listPrice: transaction.listPrice, status: transaction.status, commissionPercent: transaction.commissionPercent, gci: transaction.gci, commissionCalculationMethod: transaction.commissionCalculationMethod, commissionFlatAmount: transaction.commissionFlatAmount }); }
export function buildQualificationProgress(hireDate: Date, transactions: Record<string, any>[], config: RecruitingIncentiveConfig): QualificationProgress {
  const now = new Date(); const threshold = Number(config.gciThreshold); const eligible = Boolean(config.enabled) && Number.isFinite(threshold) && threshold > 0; const windows: Array<{ start: Date; end: Date; yearNumber: number }> = [];
  if (config.windowType === 'anniversary') { let yearNumber = 1; let start = new Date(hireDate); while (start <= now && yearNumber <= 30) { const end = addMonths(start, config.windowMonths); windows.push({ start, end, yearNumber }); start = new Date(end); yearNumber++; } } else { for (let year = hireDate.getFullYear(); year <= now.getFullYear(); year++) windows.push({ start: year === hireDate.getFullYear() ? new Date(hireDate) : startOfYear(new Date(year, 0, 1)), end: endOfYear(new Date(year, 0, 1)), yearNumber: year - hireDate.getFullYear() + 1 }); }
  const anniversaryYears = (config.recurring ? windows : windows.slice(0, 1)).map(({ start, end, yearNumber }) => { let closedGci = 0; let pendingGci = 0; let qualifiedAt: Date | null = null; const closed = transactions.filter((transaction) => transaction.status === 'closed').map((transaction) => ({ transaction, date: recruitingDate(transaction.closedDate), gci: transactionGci(transaction) })).filter((item) => item.date && item.date >= start && item.date <= end && item.gci > 0).sort((a, b) => a.date!.getTime() - b.date!.getTime()); for (const item of closed) { closedGci += item.gci; if (!qualifiedAt && eligible && closedGci >= threshold) qualifiedAt = item.date; } for (const transaction of transactions) { if (!['pending', 'under_contract'].includes(String(transaction.status))) continue; const date = recruitingDate(transaction.contractDate); const gci = transactionGci(transaction); if (date && date >= start && date <= end && gci > 0) pendingGci += gci; } const qualified = eligible && closedGci >= threshold; return { yearNumber, windowStart: start, windowEnd: end, closedGci, pendingGci, qualified, expired: now > end, isCurrent: now >= start && now <= end, payoutEarned: qualified ? config.tier1PayoutAmount : 0, qualifiedAt } as AnniversaryYearProgress & { qualifiedAt: Date | null }; });
  const current = anniversaryYears.find((window) => window.isCurrent) ?? anniversaryYears.at(-1); const totalLifetimePayouts = anniversaryYears.reduce((sum, window) => sum + window.payoutEarned, 0); const expired = Boolean(current?.expired && !current?.isCurrent);
  return { status: !eligible || !current ? 'missing_data' : current.qualified ? 'qualified' : expired ? 'expired' : 'in_progress', closedCompanyGciGrossInWindow: current?.closedGci ?? 0, pendingCompanyGciGrossInWindow: current?.pendingGci ?? 0, remainingToThreshold: eligible ? Math.max(0, threshold - (current?.closedGci ?? 0)) : 0, progressPercentage: eligible ? Math.min(100, ((current?.closedGci ?? 0) / threshold) * 100) : 0, windowEndsAt: current?.windowEnd ?? null, timeRemainingDays: current?.windowEnd && now <= current.windowEnd ? differenceInDays(current.windowEnd, now) : null, qualifiedAt: (current as any)?.qualifiedAt ?? null, annualPayout: current?.qualified ? config.tier1PayoutAmount : 0, anniversaryYears, totalLifetimePayouts, qualifiedYearsCount: anniversaryYears.filter((window) => window.qualified).length };
}
