'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useUser } from '@/firebase';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';

type Deadline = { transactionId: string; address: string; deadlineType: string; date: string; agentName?: string | null; status: string };
type Settings = { reminderEnabled: boolean; reminderHour: number; reminderMinute: number; criticalEscalationEnabled: boolean };
const section = (title: string, entries: Deadline[], tone: string) => <Card><CardHeader><CardTitle className={`text-base ${tone}`}>{title} ({entries.length})</CardTitle></CardHeader><CardContent>{entries.length === 0 ? <p className="text-sm text-muted-foreground">None.</p> : <div className="space-y-2">{entries.map((entry) => <Link className="block rounded-md border p-3 hover:bg-muted" key={`${entry.transactionId}-${entry.deadlineType}-${entry.date}`} href={`/dashboard/transactions/new?edit=${entry.transactionId}`}><p className="font-medium">{entry.address}</p><p className="text-sm text-muted-foreground">{entry.deadlineType} — {entry.date}{entry.agentName ? ` · ${entry.agentName}` : ''}</p></Link>)}</div>}</CardContent></Card>;
export default function TransactionDeadlinesPage() {
  const { user } = useUser(); const [today, setToday] = useState<Deadline[]>([]); const [tomorrow, setTomorrow] = useState<Deadline[]>([]); const [overdue, setOverdue] = useState<Deadline[]>([]); const [settings, setSettings] = useState<Settings>({ reminderEnabled: true, reminderHour: 8, reminderMinute: 0, criticalEscalationEnabled: false }); const [message, setMessage] = useState('');
  const load = async () => { if (!user) return; const token = await user.getIdToken(); const [worklist, config] = await Promise.all([fetch('/api/admin/transaction-deadlines', { headers: { Authorization: `Bearer ${token}` } }).then((response) => response.json()), fetch('/api/admin/transaction-deadline-settings', { headers: { Authorization: `Bearer ${token}` } }).then((response) => response.json())]); if (worklist.ok) { setToday(worklist.dueToday || []); setTomorrow(worklist.dueTomorrow || []); setOverdue(worklist.overdue || []); } if (config.ok) setSettings(config.settings); };
  useEffect(() => { load().catch((error) => setMessage(error.message || 'Unable to load deadlines.')); }, [user]);
  const save = async () => { if (!user) return; const token = await user.getIdToken(); const response = await fetch('/api/admin/transaction-deadline-settings', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify(settings) }); const data = await response.json(); setMessage(data.ok ? 'Deadline reminder settings saved. Critical broker escalation remains disabled.' : data.error || 'Unable to save settings.'); };
  return <div className="mx-auto max-w-6xl space-y-5 p-4 md:p-6"><div><h1 className="text-2xl font-bold">Transaction Deadlines</h1><p className="text-sm text-muted-foreground">Staff and TC view of deadlines. Agents receive preference-aware notices the morning before and the morning of a stored deadline.</p></div>{message && <p className="rounded-md bg-muted p-3 text-sm">{message}</p>}<Card><CardHeader><CardTitle className="text-base">Reminder settings</CardTitle><CardDescription>Delivery timing is Central time. A production scheduler must invoke the secured reminder route at this time.</CardDescription></CardHeader><CardContent className="flex flex-wrap items-end gap-4"><div className="flex items-center gap-2"><Switch checked={settings.reminderEnabled} onCheckedChange={(value) => setSettings((current) => ({ ...current, reminderEnabled: value }))} /><Label>Enable deadline reminders</Label></div><div><Label htmlFor="deadline-hour">Morning hour (0–23)</Label><Input id="deadline-hour" className="mt-1 w-28" type="number" min="0" max="23" value={settings.reminderHour} onChange={(event) => setSettings((current) => ({ ...current, reminderHour: Number(event.target.value) }))} /></div><Button onClick={save}>Save settings</Button></CardContent></Card><div className="grid gap-4 lg:grid-cols-3">{section('Due Today', today, 'text-amber-700')}{section('Due Tomorrow', tomorrow, 'text-sky-700')}{section('Overdue', overdue, 'text-red-700')}</div></div>;
}
