import type {
  MemberPlan,
  Team,
  TeamMembership,
  TeamPlan,
} from '@/lib/teams/types';

const now = '2026-03-09T00:00:00.000Z';

export const CHARLES_DITCH_TEAM_ID = 'charles-ditch-team';
export const CHARLES_DITCH_TEAM_PLAN_ID = 'charles-ditch-team-plan-v1';

export const CHARLES_DITCH_THRESHOLD_MARKERS = [
  0,
  42000,
  84000,
  140000,
  168000,
  224000,
];

export const charlesDitchTeam: Team = {
  teamId: CHARLES_DITCH_TEAM_ID,
  teamName: 'Charles Ditch Team',
  leaderAgentId: 'charles-ditch',
  teamPlanId: CHARLES_DITCH_TEAM_PLAN_ID,
  status: 'active',
  office: 'Lafayette',
  createdAt: now,
  updatedAt: now,
  notes: 'Initial Smart Broker team seed example.',
};

export const charlesDitchTeamPlan: TeamPlan = {
  teamPlanId: CHARLES_DITCH_TEAM_PLAN_ID,
  teamId: CHARLES_DITCH_TEAM_ID,
  planName: 'Charles Ditch Team Plan V1',
  status: 'active',
  thresholdMetric: 'companyDollar',
  thresholdMarkers: CHARLES_DITCH_THRESHOLD_MARKERS,
  structureModel: 'leaderFirst',
  leaderStructureBands: [
    { fromCompanyDollar: 0, toCompanyDollar: 42000, leaderPercent: 70, companyPercent: 30 },
    { fromCompanyDollar: 42000, toCompanyDollar: 84000, leaderPercent: 70, companyPercent: 30 },
    { fromCompanyDollar: 84000, toCompanyDollar: 140000, leaderPercent: 70, companyPercent: 30 },
    { fromCompanyDollar: 140000, toCompanyDollar: 168000, leaderPercent: 70, companyPercent: 30 },
    { fromCompanyDollar: 168000, toCompanyDollar: 224000, leaderPercent: 70, companyPercent: 30 },
    { fromCompanyDollar: 224000, toCompanyDollar: null, leaderPercent: 90, companyPercent: 10 },
  ],
  tierCreditRules: {
    memberGetsFullCompanyDollar: true,
    leaderGetsFullCompanyDollar: true,
    teamGetsFullCompanyDollar: true,
  },
  anniversaryCycleRules: {
    cycleType: 'anniversary',
  },
  createdAt: now,
  updatedAt: now,
  notes: 'Leader-first structure. Full company-dollar credit goes to member, leader, and team.',
};

export const charlesDitchTeamMemberships: TeamMembership[] = [
  {
    membershipId: 'charles-ditch-team__charles-ditch__leader',
    teamId: CHARLES_DITCH_TEAM_ID,
    agentId: 'charles-ditch',
    role: 'leader',
    memberPlanId: 'charles-ditch-member-plan-v1',
    effectiveStart: '2026-01-01',
    effectiveEnd: null,
    activeFlag: true,
    createdAt: now,
    updatedAt: now,
    notes: 'Team leader',
  },
  {
    membershipId: 'charles-ditch-team__josh-boulanger__member',
    teamId: CHARLES_DITCH_TEAM_ID,
    agentId: 'josh-boulanger',
    role: 'member',
    memberPlanId: 'josh-boulanger-member-plan-v1',
    effectiveStart: '2026-01-01',
    effectiveEnd: null,
    activeFlag: true,
    createdAt: now,
    updatedAt: now,
    notes: null,
  },
  {
    membershipId: 'charles-ditch-team__alan-gitz__member',
    teamId: CHARLES_DITCH_TEAM_ID,
    agentId: 'alan-gitz',
    role: 'member',
    memberPlanId: 'alan-gitz-member-plan-v1',
    effectiveStart: '2026-01-01',
    effectiveEnd: null,
    activeFlag: true,
    createdAt: now,
    updatedAt: now,
    notes: null,
  },
  {
    membershipId: 'charles-ditch-team__scott-domingue__member',
    teamId: CHARLES_DITCH_TEAM_ID,
    agentId: 'scott-domingue',
    role: 'member',
    memberPlanId: 'scott-domingue-member-plan-v1',
    effectiveStart: '2026-01-01',
    effectiveEnd: null,
    activeFlag: true,
    createdAt: now,
    updatedAt: now,
    notes: null,
  },
];

export const charlesDitchMemberPlans: MemberPlan[] = [
  {
    memberPlanId: 'charles-ditch-member-plan-v1',
    teamId: CHARLES_DITCH_TEAM_ID,
    agentId: 'charles-ditch',
    planName: 'Charles Ditch Personal Ladder V1',
    status: 'active',
    thresholdMetric: 'companyDollar',
    thresholdMarkers: CHARLES_DITCH_THRESHOLD_MARKERS,
    payoutBands: [
      { fromCompanyDollar: 0, toCompanyDollar: 42000, memberPercent: 70 },
      { fromCompanyDollar: 42000, toCompanyDollar: 84000, memberPercent: 70 },
      { fromCompanyDollar: 84000, toCompanyDollar: 140000, memberPercent: 70 },
      { fromCompanyDollar: 140000, toCompanyDollar: 168000, memberPercent: 70 },
      { fromCompanyDollar: 168000, toCompanyDollar: 224000, memberPercent: 70 },
      { fromCompanyDollar: 224000, toCompanyDollar: null, memberPercent: 90 },
    ],
    createdAt: now,
    updatedAt: now,
    notes: 'Leader personal ladder',
  },
  {
    memberPlanId: 'josh-boulanger-member-plan-v1',
    teamId: CHARLES_DITCH_TEAM_ID,
    agentId: 'josh-boulanger',
    planName: 'Josh Boulanger Member Ladder V1',
    status: 'active',
    thresholdMetric: 'companyDollar',
    thresholdMarkers: CHARLES_DITCH_THRESHOLD_MARKERS,
    payoutBands: [
      { fromCompanyDollar: 0, toCompanyDollar: 42000, memberPercent: 45 },
      { fromCompanyDollar: 42000, toCompanyDollar: 84000, memberPercent: 50 },
      { fromCompanyDollar: 84000, toCompanyDollar: 140000, memberPercent: 60 },
      { fromCompanyDollar: 140000, toCompanyDollar: 168000, memberPercent: 65 },
      { fromCompanyDollar: 168000, toCompanyDollar: 224000, memberPercent: 70 },
      { fromCompanyDollar: 224000, toCompanyDollar: null, memberPercent: 80 },
    ],
    createdAt: now,
    updatedAt: now,
    notes: null,
  },
  {
    memberPlanId: 'alan-gitz-member-plan-v1',
    teamId: CHARLES_DITCH_TEAM_ID,
    agentId: 'alan-gitz',
    planName: 'Alan Gitz Member Ladder V1',
    status: 'active',
    thresholdMetric: 'companyDollar',
    thresholdMarkers: CHARLES_DITCH_THRESHOLD_MARKERS,
    payoutBands: [
      { fromCompanyDollar: 0, toCompanyDollar: 42000, memberPercent: 45 },
      { fromCompanyDollar: 42000, toCompanyDollar: 84000, memberPercent: 50 },
      { fromCompanyDollar: 84000, toCompanyDollar: 140000, memberPercent: 60 },
      { fromCompanyDollar: 140000, toCompanyDollar: 168000, memberPercent: 65 },
      { fromCompanyDollar: 168000, toCompanyDollar: 224000, memberPercent: 70 },
      { fromCompanyDollar: 224000, toCompanyDollar: null, memberPercent: 80 },
    ],
    createdAt: now,
    updatedAt: now,
    notes: null,
  },
  {
    memberPlanId: 'scott-domingue-member-plan-v1',
    teamId: CHARLES_DITCH_TEAM_ID,
    agentId: 'scott-domingue',
    planName: 'Scott Domingue Member Ladder V1',
    status: 'active',
    thresholdMetric: 'companyDollar',
    thresholdMarkers: CHARLES_DITCH_THRESHOLD_MARKERS,
    payoutBands: [
      { fromCompanyDollar: 0, toCompanyDollar: 42000, memberPercent: 65 },
      { fromCompanyDollar: 42000, toCompanyDollar: 84000, memberPercent: 70 },
      { fromCompanyDollar: 84000, toCompanyDollar: 140000, memberPercent: 75 },
      { fromCompanyDollar: 140000, toCompanyDollar: 168000, memberPercent: 80 },
      { fromCompanyDollar: 168000, toCompanyDollar: 224000, memberPercent: 85 },
      { fromCompanyDollar: 224000, toCompanyDollar: null, memberPercent: 90 },
    ],
    createdAt: now,
    updatedAt: now,
    notes: null,
  },
];
